openapi: 3.0.2
info:
  title: Test API
  version: 0.0.0
paths:
  /login:
    post:
      operationId: login
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginRequest'
        required: true
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginResponse'
  /whoami:
    get:
      operationId: whoami
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/whoamiRequest'
        required: true
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/whoamiResponse'
components:
  schemas:
    loginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    loginResponse:
      type: object
      properties:
        sessionId:
          type: string
      required:
        - sessionId
    whoamiRequest:
      type: object
    whoamiResponse:
      type: object
      properties:
        username:
          type: string
      required:
        - username
